# Phi-3 Mini 4K Instruct LoRA Fine-tuning with BOS Token Zeroing
# This configuration adds BOS tokens and zeros out their embeddings during training

### Model
model_name_or_path: microsoft/Phi-3-mini-4k-instruct
trust_remote_code: true

### Method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all  # Apply LoRA to all linear layers
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.1

### Dataset
dataset: alpaca_en
template: phi
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### Output
output_dir: saves/phi3-bos-zero-lora-alpaca
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### Train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 5.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### Eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 250
save_total_limit: 2
metric_for_best_model: eval_loss

### BOS Token Zeroing Configuration
use_bos_zero_training: true