### model
model_name_or_path: microsoft/Phi-3-mini-4k-instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: freeze
freeze_trainable_modules: all
rmsnorm_only_training: true
use_rmsnorm_regularization: true
rmsnorm_reg_layers: "2,4"
rmsnorm_reg_weight: 0.01
rmsnorm_reg_target_norm: 0.0

### dataset
dataset: identity
template: phi
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./saves/phi3-rmsnorm-reg
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 250