### model
model_name_or_path: microsoft/Phi-3-mini-4k-instruct
adapter_name_or_path: null

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.1

### dataset
dataset: tulu_3_sft_mixture
template: phi
cutoff_len: 1024
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./saves/phi3-variance-reg-tulu3
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 5.0e-05
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

### RMSNorm Variance Regularization
use_variance_regularization: true
variance_reg_layers: "model.layers.0.post_attention_layernorm,model.layers.1.post_attention_layernorm,model.layers.2.post_attention_layernorm"
variance_reg_weight: 0.01
variance_reg_target: 1.0
variance_reg_norm_type: "l2"